### ISSUE TITLE
Permission to use name for "C" conversion

### ISSUE THREAD

**Issue by ztalbot2000** [nollan/zerofile#1]
hi Nolan,

  Your License says to use your repo name and name I must contact you.  I converted your tool from Go to "C" so that I can compile it easily on my Mac. The functionality is 100% the same, with the addition of a Mac test script that creates a sized Volume for zeroFile to run on, without testing it on a real drive.

I just wanted your permission to commit my repo with the name zeroFile and with credit to you.  The License would remain the same. Otherwise, I do not know if it's possible to publish my repo. Sorry, just trying to do the right thing. 

thanks,
John Talbot

**Comment by nollan** [comment]
You have my permission, have fun!

**Comment by ztalbot2000** [comment]
Hi,

Thank you for your permission.  The new repo is
https://github.com/ztalbot2000/zerofile.git. If you have concerns, please
let me know.

Thank you,
John Talbot
